### ISSUE TITLE
Weights error not compatible with provided weight shape.

### ISSUE THREAD

**Issue by springcoil** [michaelosthege/tornado-compute#1]
```
Traceback (most recent call last):
  File "/Users/peadarcoyle/anaconda/envs/py35/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/Users/peadarcoyle/anaconda/envs/py35/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/peadarcoyle/anaconda/envs/py35/lib/python3.5/site-packages/dualprocessing/__init__.py", line 104, in __start__
    processor = processorConstructor(*pc_args, **pc_kwargs)
  File "StartService.py", line 53, in makePipeline
    processor = Pipeline.Pipeline("vgg16_weights.h5")
  File "/Users/peadarcoyle/Code/tornado-compute/tornado-compute/Pipeline.py", line 25, in __init__
    self.VGG = self.get_vgg(weights_path, download_from)
  File "/Users/peadarcoyle/Code/tornado-compute/tornado-compute/Pipeline.py", line 36, in get_vgg
    vgg = buddy.get_model(224, 224, weights_path)
  File "/Users/peadarcoyle/anaconda/envs/py35/lib/python3.5/site-packages/keras_vgg_buddy/models.py", line 76, in get_model
    weights_path=weights_path, last_layer=last_layer)
  File "/Users/peadarcoyle/anaconda/envs/py35/lib/python3.5/site-packages/keras_vgg_buddy/models.py", line 96, in add_vgg_to_layer
    layer.set_weights(weights)
  File "/Users/peadarcoyle/anaconda/envs/py35/lib/python3.5/site-packages/keras/engine/topology.py", line 1154, in set_weights
    'provided weight shape ' + str(w.shape))
ValueError: Layer weight shape (3, 3, 224, 64) not compatible with provided weight shape (64, 3, 3, 3)```

Keras 2.0.2 and all other requirements.

**Comment by michaelosthege** [comment]
Since there are some breaking changes in the keras 2.0 API, the provided VGG weights do not work anymore.

Options:
+ use keras < 2.0
+ substitute with an updated weights file

I would totally help and update it right away, but my internet speed right now averages at 24 kbps. (I'm on my phone here..)

**Comment by springcoil** [comment]
I'll try it with an updated weights file.
